name: 'Test'

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  python:
    name: 'Test'
    runs-on: ubuntu-latest
    environment: production
    defaults:
      run:
        shell: bash

    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install dependencies
        run: python -m pip install --upgrade pip boto3 simplejson botocore moto

      - name: Test with unittest
        working-directory: ./lambda/IncrementVisits
        run: python -m unittest ./test_IncrementVisits.py
        env:
          AWS_ACCESS_KEY_ID: dummy-access-key
          AWS_SECRET_ACCESS_KEY: dummy-access-key-secret
          AWS_DEFAULT_REGION: eu-west-2

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12
        with:
          # This will add a CLI output to the console
          output_format: cli
          output_file_path: console
          quiet: true